config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to
  # something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default
  # of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products, only: [:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  def show
    @product = Spree::Product.find(params[:id])
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "BIGBAG Store"
    if page_title.blank?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end
end

app/views/layouts/_footer.html.erb
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.current.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header clearfix">
  <%= render 'layouts/topbar' %>
  <%= render 'layouts/navbar' %>
</div>

app/views/layouts/_light_section.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= yield(:title) %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_index_path %>
          </li>
          <li class="active"><%= yield(:title) %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_login_modal.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-main navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("img/logo.png", :alt => ""), potepan_index_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", potepan_index_path %></li>
        <li class="dropdown megaDropMenu active">
          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/_sign_up_modal.html.erb
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">Enter Email</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">Password</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">Confirm Password</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_topbar.html.erb
<div class="topBar">
  <div class="container">
    <div class="row">
      <div class="col-md-6 hidden-sm hidden-xs">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
      <div class="col-md-6 col-xs-12">
        <ul class="list-inline pull-right">
          <li><span><a data-toggle="modal" href='#login'>Log in</a><small>or</small><a data-toggle="modal" href='#signup'>Create an account</a></span></li>
          <li class="dropdown searchBox">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <form  id="form01" action="product-grid-left-sidebar.html" method="post">
                <li>
                  <span class="input-group">
                    <input type="text" name="searchWord" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span onclick="FormSubmit();" class="input-group-addon addPointer" id="basic-addon2">Search</span>
                  </span>
                </li>
              </form>
            </ul>
          </li>
          <li class="dropdown">
            <a href="cart-page.html" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- SITE TITTLE -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <!-- PLUGINS CSS STYLE -->

    <!-- GOOGLE FONT -->
    <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

    <!-- CUSTOM CSS -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="main-wrapper">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= render 'layouts/login_modal' %>
    <%= render 'layouts/sign_up_modal' %>
    <%= render 'layouts/product_quick_view' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>

<%= render 'layouts/light_section' %>

<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <% @product.images.each_with_index do |image, i| %>
                  <div class="item <%= "active" if i.zero? %>" data-thumb="<%= i %>">
                    <%= image_tag image.attachment(:large) %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="clearfix">
              <div id="thumbcarousel" class="carousel slide" data-interval="false">
                <div class="carousel-inner">
                  <% @product.images.each_with_index do |image, i| %>
                    <div data-target="#carousel" data-slide-to="<%= i %>" class="thumb">
                      <%= image_tag image.attachment(:small) %>
                    </div>
                  <% end %>
                </div>
                <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <li><a href="product_grid_left_sidebar.html"><i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る</a></li>
            </ul>
            <h2><%= @product.name %></h2>
            <h3><%= @product.display_price %></h3>
            <p><%= @product.description %></p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">S</option>
                <option value="1">M</option>
                <option value="2">L</option>
                <option value="3">XL</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row productsContent">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>関連商品</h4>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="productBox">
          <div class="productImage clearfix">
            <%= image_tag("img/products/products-01.jpg", :alt => "products-img") %>
          </div>
          <div class="productCaption clearfix">
           <h5>Nike Sportswear</h5>
           <h3>199円</h3>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="productBox">
          <div class="productImage clearfix">
            <%= image_tag("img/products/products-02.jpg", :alt => "products-img") %>
          </div>
          <div class="productCaption clearfix">
           <h5>Dip Dyed Sweater</h5>
           <h3>249円</h3>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="productBox">
          <div class="productImage clearfix">
            <%= image_tag("img/products/products-03.jpg", :alt => "products-img") %>
          </div>
          <div class="productCaption clearfix">
           <h5>Scarf Ring Corner</h5>
           <h3>179円</h3>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="productBox">
          <div class="productImage clearfix">
            <%= image_tag("img/products/products-04.jpg", :alt => "products-img") %>
          </div>
          <div class="productCaption clearfix">
           <h5>Sun Buddies</h5>
           <h3>149円</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/sample/blog_single_left_sidebar.html.erb
<% provide(:title, "Blog Single Sidebar") %>

<%= render 'layouts/light_section' %>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix blogPage singleBlog">
  <div class="container">
    <div class="row">
      <div class="col-md-9 col-sm-8 col-md-push-3 col-sm-push-4 col-xs-12">
        <div class="row">
          <div class="col-xs-12">
            <div class="thumbnail">
              <%= image_tag("img/blog/blog-01.jpg", :alt => "blog-image") %>
              <div class="caption">
                <div class="row">
                  <div class="col-md-12 col-sm-12 col-xs-12">
                    <h3>記事タイトル </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p>

                    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. </p>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p>

                    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. </p>
                  </div>
                </div>
              </div>
              <ul class="pager">
                <li class="previous"><a href="#">前の記事へ</a></li>
                <li class="next"><a href="#">次の記事へ</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-4 col-md-pull-9 col-sm-pull-8 col-xs-12 sideBar">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search" aria-describedby="basic-addon2">
          <a href="#" class="input-group-addon" id="basic-addon2"><i class="fa fa-search"></i></a>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">カテゴリー</div>
          <div class="panel-body">
            <ul class="list-unstyle sidebar-list">
              <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>アクセサリー <span>(6)</span></a></li>
              <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>バッグ <span>(6)</span></a></li>
              <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>洋服 <span>(25)</span></a></li>
              <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>ベッド &amp; バス <span>(2)</span></a></li>
              <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>スイミング <span>(5)</span></a></li>
              <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>スポーツウェア &amp; シューズ <span>(3)</span></a></li>
            </ul>
          </div>
        </div>
        <div class="panel panel-default recentBlogPosts">
          <div class="panel-heading">最新記事</div>
          <div class="panel-body">
            <div class="media">
              <a class="media-left" href="blog_single_right_sidebar.html">
                <%= image_tag("img/blog/blog-small-01.jpg", :class => "media-object", :alt => "Image") %>
              </a>
              <div class="media-body">
                <h4 class="media-heading"><a href="blog_single_right_sidebar.html">記事タイトル（20文字）</a></h4>
                <p><i class="fa fa-calendar" aria-hidden="true"></i>2016/5/5</p>
              </div>
            </div>
            <div class="media">
              <a class="media-left" href="blog_single_right_sidebar.html">
                <%= image_tag("img/blog/blog-small-02.jpg", :class => "media-object", :alt => "Image") %>
              </a>
              <div class="media-body">
                <h4 class="media-heading"><a href="blog_single_right_sidebar.html">記事タイトル（20文字）</a></h4>
                <p><i class="fa fa-calendar" aria-hidden="true"></i>2016/5/5</p>
              </div>
            </div>
            <div class="media">
              <a class="media-left" href="blog_single_right_sidebar.html">
                <%= image_tag("img/blog/blog-small-03.jpg", :class => "media-object", :alt => "Image") %>
              </a>
              <div class="media-body">
                <h4 class="media-heading"><a href="blog_single_right_sidebar.html">記事タイトル（20文字）</a></h4>
                <p><i class="fa fa-calendar" aria-hidden="true"></i>2016/5/5</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/sample/cart_page.html.erb
<% provide(:title, "Cart Page") %>

<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeaderImage">
  <div class="container">
    <div class="tableBlock">
      <div class="row tableInner">
        <div class="col-xs-12">
          <div class="page-title">
            <h2>cart</h2>
            <ol class="breadcrumb">
              <li>
                <%= link_to "Home", potepan_index_path %>
              </li>
              <li class="active">cart</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix cartListWrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="cartListInner">
          <form action="#">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th></th>
                    <th>商品名</th>
                    <th>価格</th>
                    <th>数</th>
                    <th>小計</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="updateArea">
             <!--  <div class="input-group">
                <input type="text" class="form-control" placeholder="I have a discount coupon" aria-describedby="basic-addon2">
                <a href="#" class="btn input-group-addon" id="basic-addon2">apply coupon</a>
              </div> -->
              <a href="#" class="btn">アップデート</a>
            </div>
            <div class="totalAmountArea">
              <div class="col-sm-4 col-sm-offset-8 col-xs-12">
                <ul class="list-unstyled">
                  <li>小計 <span>792円</span></li>
                  <li>消費税 <span>18円</span></li>
                  <li>総計 <span class="grandTotal">810円</span></li>
                </ul>
              </div>
            </div>
            <div class="checkBtnArea">
              <a href="checkout_step_1.html" class="btn btn-primary btn-block">購入する<i class="fa fa-arrow-circle-right" aria-hidden="true"></i></a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/sample/checkout_complete.html.erb
<% provide(:title, "Thanks Message") %>

<%= render 'layouts/light_section' %>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix setp5">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="thanksContent">
          <h2>Thank You !! <small>ご注文ありがとうございます。</small></h2>
          <h3>Shipping Details</h3>
          <div class="thanksInner">
            <div class="row">
              <div class="col-sm-6 col-xs-12 tableBlcok">
                <address>
                  <span>Shipping address:</span> <a href="mailto:potepan@potepancamp.com">potepan@potepancamp.com</a> <br>
                  <span>Email:</span> <a href="mailto:potepan@potepancamp.com">potepan@potepancamp.com</a> <br>
                  <span>Phone:</span> +884 5452 6432
                </address>
              </div>
              <div class="col-sm-6 col-xs-12">
                <div class="well">
                  <h2><small>Order ID</small>9547</h2>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/sample/privacy_policy.html.erb
<% provide(:title, "Privacy Policy") %>

<%= render 'layouts/light_section' %>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix genricContent">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h3>プライバシーポリシー</h3>
        <p>株式会社 xxx（以下「当社」）は、以下のとおり個人情報保護方針を定め、個人情報保護の仕組みを構築し、全従業員に個人情報保護の重要性の認識と取組みを徹底させることにより、個人情報の保護を推進致します。</p>

        <h5>個人情報の管理</h5>
        <p>当社は、お客さまの個人情報を正確かつ最新の状態に保ち、個人情報への不正アクセス・紛失・破損・改ざん・漏洩などを防止するため、セキュリティシステムの維持・管理体制の整備・社員教育の徹底等の必要な措置を講じ、安全対策を実施し個人情報の厳重な管理を行ないます。</p>

        <h5>個人情報の利用目的</h5>
        <p>お客さまからお預かりした個人情報は、当社からのご連絡や業務のご案内やご質問に対する回答として、電子メールや資料のご送付に利用いたします。</p>

        <h5>個人情報の第三者への開示・提供の禁止</h5>
        <p>当社は、お客さまよりお預かりした個人情報を適切に管理し、次のいずれかに該当する場合を除き、個人情報を第三者に開示いたしません。<br><br>
        ・お客さまの同意がある場合<br>
        ・お客さまが希望されるサービスを行なうために当社が業務を委託する業者に対して開示する場合<br>
        ・法令に基づき開示することが必要である場合</p>

        <h5>個人情報の安全対策</h5>
        <p>当社は、個人情報の正確性及び安全性確保のために、セキュリティに万全の対策を講じています。</p>

        <h5>ご本人の照会</h5>
        <p>お客さまがご本人の個人情報の照会・修正・削除などをご希望される場合には、ご本人であることを確認の上、対応させていただきます。</p>

        <h5>法令、規範の遵守と見直し</h5>
        <p>当社は、保有する個人情報に関して適用される日本の法令、その他規範を遵守するとともに、本ポリシーの内容を適宜見直し、その改善に努めます。</p>

        <h5>お問い合せ</h5>
        <p>当社の個人情報の取扱に関するお問い合せは下記までご連絡ください。<br>
        株式会社 xxx <br>
        〒xxx-xxxx　xx県xx市xx町x-x-x <br>
        TEL:XXX-XXX-XXXX FAX:XXX-XXX-XXXX <br>
        Mail:info@example.co.jp <br>
        </p>

      </div>
    </div>
  </div>
</section>